# Generated by Django 2.1.3 on 2018-11-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('marks', models.FloatField(default=0)),
                ('q_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student_id', 'course_id', 'q_name')},
        ),
    ]
