# Generated by Django 2.1.3 on 2018-11-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csvfile',
        ),
    ]
