# Generated by Django 2.1.3 on 2018-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_delete_csvfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
