# Generated by Django 2.1.3 on 2018-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='req_file',
            field=models.FileField(upload_to='home/phani/Documents/'),
        ),
    ]
