# Generated by Django 2.1.3 on 2018-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20181111_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='req_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
