# Generated by Django 2.1.3 on 2018-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, unique=True)),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('credits', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='course_taken_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_emailid', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=15)),
                ('year', models.IntegerField(max_length=4)),
                ('semester', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_emailid', models.CharField(max_length=100, unique=True)),
                ('professor_description', models.CharField(max_length=200)),
                ('professor_photo', models.FileField(upload_to='')),
                ('professor_fullname', models.CharField(max_length=100)),
            ],
        ),
    ]
