# Generated by Django 2.1.3 on 2018-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181103_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course_taken_by',
            name='year',
            field=models.IntegerField(),
        ),
    ]
