# Generated by Django 2.1.3 on 2018-11-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181103_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_details',
        ),
        migrations.DeleteModel(
            name='course_taken_by',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
