# Generated by Django 2.1.3 on 2018-11-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_auto_20181105_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, unique=True)),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_taken_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_emailid', models.CharField(max_length=100, unique=True)),
                ('professor_description', models.CharField(max_length=150)),
                ('professor_photo', models.ImageField(upload_to='')),
                ('professor_fullname', models.CharField(max_length=50)),
                ('professor_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='course_taken_by',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
        ),
    ]
