# Generated by Django 2.1.3 on 2018-11-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181105_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_details',
        ),
        migrations.RemoveField(
            model_name='course_taken_by',
            name='professor_id',
        ),
        migrations.DeleteModel(
            name='course_taken_by',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
