# Generated by Django 2.1.3 on 2018-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181105_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
