# Generated by Django 2.1.3 on 2018-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181108_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
