# Generated by Django 2.1.3 on 2018-11-11 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0010_auto_20181111_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_description', models.CharField(max_length=150)),
                ('professor_photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='course_taken_by',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course_taken_by',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professor',
        ),
        migrations.RenameModel(
            old_name='course_details',
            new_name='course',
        ),
        migrations.DeleteModel(
            name='course_taken_by',
        ),
        migrations.DeleteModel(
            name='professor',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AddField(
            model_name='professor_profile',
            name='course',
            field=models.ManyToManyField(to='login.course'),
        ),
        migrations.AddField(
            model_name='professor_profile',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
