# Generated by Django 2.1.3 on 2018-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20181111_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_profile',
            old_name='course',
            new_name='professor_course',
        ),
        migrations.AlterField(
            model_name='professor_profile',
            name='professor_photo',
            field=models.ImageField(upload_to='media_/photos'),
        ),
    ]
