# Generated by Django 2.1.3 on 2018-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20181117_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_profile',
            name='professor_photo',
            field=models.ImageField(blank=True, upload_to='media_/photos'),
        ),
    ]
