# Generated by Django 2.1.3 on 2018-11-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_file', models.FileField(upload_to='media_')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=15)),
                ('student_name', models.CharField(max_length=15)),
                ('prof_id', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=15)),
                ('student_id', models.CharField(default=0, max_length=15)),
                ('course_id', models.CharField(default=0, max_length=15)),
                ('prof_id', models.CharField(default=0, max_length=15)),
                ('marks', models.FloatField(default=0)),
                ('q_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student_id', 'course_id', 'prof_id', 'q_name', 'student_name')},
        ),
    ]
