# Generated by Django 2.1.3 on 2018-12-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_difficulty', models.CharField(default='-', max_length=15)),
                ('course_risk', models.CharField(default='-', max_length=15)),
                ('course_average', models.FloatField(default=0)),
                ('exam_difficulty', models.CharField(default='-', max_length=15)),
                ('exam_cheat_risk', models.CharField(default='-', max_length=15)),
                ('exam_average', models.FloatField(default=0)),
                ('quartile_1', models.FloatField(default=0)),
                ('quartile_2', models.FloatField(default=0)),
                ('quartile_3', models.FloatField(default=0)),
                ('course_student_list', models.CharField(default='-', max_length=150)),
                ('exam_student_list', models.CharField(default='-', max_length=150)),
                ('needy_student_list', models.CharField(default='-', max_length=150)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
