# Generated by Django 2.1.3 on 2018-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181204_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='label',
            field=models.CharField(default='-', max_length=90),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='performance',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='persistance',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
