# Generated by Django 2.1.3 on 2018-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181206_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('class_rank', models.IntegerField(default=0)),
                ('exam_rank', models.IntegerField(default=0)),
                ('lab_rank', models.IntegerField(default=0)),
                ('asgn_rank', models.IntegerField(default=0)),
                ('oth_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz_enrollments',
            name='professor',
        ),
        migrations.DeleteModel(
            name='quiz_enrollments',
        ),
    ]
