# Generated by Django 2.1.3 on 2018-12-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181206_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_ranks',
            name='best_exam',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='student_ranks',
            name='best_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_ranks',
            name='worst_exam',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='student_ranks',
            name='worst_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='q_name',
            field=models.CharField(max_length=50),
        ),
    ]
