# Generated by Django 2.1.3 on 2018-12-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181207_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_ranks',
            old_name='worst_rank',
            new_name='worst_marks',
        ),
    ]
