# Generated by Django 2.1.3 on 2018-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181207_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_ranks',
            name='overall',
            field=models.IntegerField(default=0),
        ),
    ]
