# Generated by Django 2.1.3 on 2018-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_student_ranks_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_ranks',
            name='course',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
