# Generated by Django 2.1.3 on 2018-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_student_ranks_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dashboard',
            name='course',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
