# Generated by Django 2.1.3 on 2018-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_course_dashboard_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dashboard',
            name='average_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course_dashboard',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
    ]
