# Generated by Django 2.1.3 on 2018-12-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20181208_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_dashboard',
            name='average_marks',
        ),
        migrations.RemoveField(
            model_name='course_dashboard',
            name='max_marks',
        ),
    ]
