# Generated by Django 2.1.3 on 2018-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20181208_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='-', max_length=150)),
                ('quiz_name', models.CharField(default='-', max_length=150)),
                ('max_marks', models.IntegerField(default=0)),
                ('avg_marks', models.IntegerField(default=0)),
            ],
        ),
    ]
