# Generated by Django 2.1.3 on 2018-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_course_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_exams',
            name='avg_marks',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
