# Generated by Django 2.1.3 on 2018-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20181208_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='q_name',
            field=models.CharField(max_length=150),
        ),
    ]
