# Generated by Django 2.1.3 on 2018-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='classaverage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
