# Generated by Django 2.1.3 on 2018-11-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20181116_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='classaverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
