# Generated by Django 2.1.3 on 2018-11-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, unique=True)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='professor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_description', models.CharField(max_length=150)),
                ('professor_photo', models.ImageField(default='media_/photos/download.png', upload_to='media_/photos')),
                ('professor_course', models.CharField(max_length=100)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
