# Generated by Django 2.1.3 on 2018-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='media_/photos/course1.jpg', upload_to='media_/photos'),
        ),
    ]
