# Generated by Django 2.1.3 on 2018-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20181208_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='media_/photos/course.jpg', upload_to='media_/photos'),
        ),
    ]
