# Generated by Django 2.1.3 on 2018-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20181117_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_profile',
            name='professor_photo',
            field=models.ImageField(default='media_/photos/download.png', upload_to='media_/photos'),
        ),
    ]
